// NextGen Ita — AI Bits Config
// Manage which posts appear on bits.html
// Use admin.html to toggle and generate articles visually

window.NEXTGEN_POSTS = [
  {
    id: "10",
    published: true,
    date: "Apr 2026",
    tag: "AI",
    title: "Notes on LLM Research",
    excerpt: "A short take on the latest LLM research and what it means for builders. Read the full thread on LinkedIn.",
    file: "",
    readTime: "2 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-llm-research-activity-7444311234470100992-Vmth",
    text: `A short take on the latest LLM research and what it means for builders. Click "View original on LinkedIn" below to read the full post and join the discussion.`
  },
  {
    id: "09",
    published: true,
    date: "May 2026",
    tag: "AI",
    title: "AI Just Rewrote the Rules of Drug Approval",
    excerpt: "Last week the FDA ran the first real-time clinical trial in history. Patient data streaming live to regulators. Their chief AI officer says it could cut 20-30% off trial time.",
    file: "",
    readTime: "3 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-genai-pharma-activity-7457002355696447488-X8Of",
    text: `Last week the FDA ran the first real-time clinical trial in history. Patient data streaming live to regulators as it's collected, no waiting months for sponsors to compile reports, no stop-and-go between phases. Their chief AI officer said it could cut 20 to 30% off trial time. 10 to 12 years to bring a drug to market is one of those numbers that gets repeated so often it starts to feel inevitable. This announcement is a reminder that a meaningful part of that timeline was also a process problem, not just a scientific one. The organizations making real progress are the ones that stopped asking 'should we invest in AI' and started asking 'what do we need to build so AI actually works here.' Data infrastructure, governance, people who understand both the science and the technology. The FDA moving on real-time trials signals the regulatory environment is catching up. The gap between pharma companies that are ready and those still in pilot mode is about to get a lot more visible.`
  },
  {
    id: "07",
    published: true,
    date: "Apr 2026",
    tag: "AI",
    title: "Claude Design Dropped. The Capabilities Are Insane.",
    excerpt: "We are living in weird, fast times. Disruption is already here. Being alive right now is a wild experience, but let's be honest: it's hard to keep up.",
    file: "",
    readTime: "2 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_nextgenita-ai-claudedesign-ugcPost-7451283675834503168-5zGk",
    text: `Claude Design by Anthropic dropped yesterday. The capabilities, UX, and slides are insane. We are living in weird, fast times. Disruption is already here. Being alive right now is a wild experience, but let's be honest: it's hard to keep up. Like my guests on #NextGenITA said yesterday: "staying in the AI field might be a struggle because everything moves too fast." And sometimes, it is exhausting to stay updated, even if I put all my efforts towards it. I look at where we are going and I feel a mix of curiosity and fear. It's exciting to see what we can build, but also strange to think how much everything will change so soon. I'm curious to see what happens next, even if it feels a bit overwhelming. It's going to be a different world very, very, very soon. In Italian: non mi aspettavo fossimo già a questo punto.`
  },
  {
    id: "08",
    published: true,
    date: "Apr 2026",
    tag: "AI",
    title: "OpenAI Just Confirmed the Direction. Twice in One Week.",
    excerpt: "April 14: strategic partnership with Novo Nordisk, AI embedded across the whole company. April 16: GPT-Rosalind, OpenAI's first model built for biology and drug discovery.",
    file: "",
    readTime: "4 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-genai-pharma-share-7456844670950629376-0Ij1",
    text: `Last week I wrote about Anthropic buying a biotech startup for $400 million. Now OpenAI confirmed the direction. Twice in one week. April 14th: a strategic partnership with Novo Nordisk. AI embedded across the whole company, from drug discovery to manufacturing to commercial operations. Full integration by end of 2026. Also: OpenAI will upskill Novo Nordisk's entire global workforce. That part is underreported and probably the hardest to execute. April 16th: GPT-Rosalind, their first model built specifically for biology and drug discovery. Named after Rosalind Franklin, whose work helped crack the structure of DNA. It reasons through biology, not just text about biology. Launch partners include Amgen, Moderna, the Allen Institute and Thermo Fisher Scientific. Access restricted to vetted institutions, because a model that reasons about molecular biology at this level is dual-use by definition. The pattern I highlighted for months is getting clearer. The big AI labs are not just selling API access to pharma. They are building vertical infrastructure, with domain-specific models and enterprise partnerships that go deep into operations. The gap between announcement and what actually changes on the ground is still real. But this is the kind of move that has to happen if pharma is ever going to operate at a different level: AI-powered Pharma. The results are still pending. The direction is not.`
  },
  {
    id: "02",
    published: true,
    date: "Apr 2026",
    tag: "AI",
    title: "What the Stanford AI Index 2026 Actually Says",
    excerpt: "The performance gap between top models has shrunk to 2.7%. Global adoption is moving faster than the internet. Here are the data points that matter.",
    file: "bit-02.html",
    readTime: "3 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_the-2026-ai-index-report-stanford-aielaborationfavilli-ugcPost-7449630213459812352-coxL",
    text: `The new 2026 AI Index from Stanford Institute for Human-Centered Artificial Intelligence (HAI) is officially out. The data highlights a massive shift: the performance gap between top models has shrunk to a razor-thin 2.7% (Anthropic at the top), and global adoption is moving faster than the internet ever did. A reflection for organizations: How can we use these insights to actually evolve our business models, rather than just automating what we have?`
  },
  {
    id: "01",
    published: true,
    date: "Apr 2026",
    tag: "AI",
    title: "Anthropic Paid $400M for a Problem",
    excerpt: "Fewer than 10 people. No product. No revenue. Here is what Anthropic actually bought, and why pharma is the next AI infrastructure war.",
    file: "bit-01.html",
    readTime: "4 min",
    author: "Matteo Favilli",
    image: "",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-pharma-biotech-ugcPost-7447809879718699008-9o_n",
    text: `Last week Anthropic paid $400 million for a startup that was eight months old. Fewer than 10 people. No product. No revenue. I spend a lot of time with pharma clients leading AI projects. One thing comes up constantly: the models don't speak biology. They speak English. That's the gap Coefficient Bio was working on. Anthropic didn't buy a product but paid $400 million for a problem most of the industry is still pretending doesn't exist.`
  },
  {
    id: "03",
    published: true,
    date: "Mar 2026",
    tag: "AI",
    title: "AI's Memory Problem, and Google's Fix",
    excerpt: "Every AI conversation has a weight limit. Google just published a technique that shrinks that memory by 6x without retraining the model. Here is what it means.",
    file: "bit-03.html",
    readTime: "3 min",
    author: "Matteo Favilli",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-llm-research-share-7444184604892209152-NcPo",
    text: `We've all felt it: that brutal typing lag once an AI chat gets too long. Every time you chat with an AI, it has to store the whole conversation in its short-term memory. The longer the conversation, the more it eats up, until the system gets slow or the cost to run it just doesn't make sense anymore. Google just put out a paper on TurboQuant (using techniques like PolarQuant and QJL) to deal with this. The idea: instead of storing that memory in a complex, bulky way, they found a mathematical shortcut to shrink it by 6x. No need to retrain any LLM. Making AI 6x lighter means it might actually work on a normal office server or even your phone, without needing a giant data center in the background. There's a trade-off, though. To make it this light, the AI has to forget the details it thinks don't matter. It's a very human compromise: we filter out the noise so we can focus.`
  },
  {
    id: "04",
    published: true,
    date: "Mar 2026",
    tag: "AI",
    title: "A 20-Year-Old Built This in 10 Days. Then It Got Complicated.",
    excerpt: "MiroFish generates thousands of AI agents with distinct personalities and memories. Built by a student, vibe coding only. $4M raised in 24 hours. Then you start thinking about Meta's data.",
    file: "bit-04.html",
    readTime: "4 min",
    author: "Matteo Favilli",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-aiagents-generativeai-share-7442375971992666112-ZiSJ",
    text: `You are already being simulated. MiroFish is a tool built by a 20-year-old student in 10 days, vibe coding only. Feed it documents and it constructs knowledge graphs, generates thousands of AI agents with distinct personalities and memories, and simulates human interactions. It raised $4 million in 24 hours with 33,000+ GitHub stars. Then think about Meta's behavioral datasets spanning 3 billion users, including reading time, scroll patterns, and messaging data. Cambridge Analytica operated with 87 million profiles and a fraction of today's AI capabilities. Modern AI simulation combined with contemporary behavioral data represents unprecedented predictive power over individual behavior. How did we get here so fast?`
  },
  {
    id: "05",
    published: true,
    date: "Mar 2026",
    tag: "AI",
    title: "The Chat Interface Was Just the Lobby",
    excerpt: "OpenClaw proved something the big labs did not want to prove: for most real tasks, cheaper models on a Mac Mini are good enough. The competition has shifted. It is not about the model anymore.",
    file: "bit-05.html",
    readTime: "4 min",
    author: "Matteo Favilli",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-aiagents-generativeai-share-7441788833072979968-aen_",
    text: `Six months ago nobody had heard of OpenClaw. One Austrian developer built it alone. Last week Jensen Huang dedicated part of his NVIDIA GTC keynote to it and called it "the most popular open-source project in the history of humanity." But that's not the point. For years, the big AI labs raised hundreds of billions on a single bet: that their models were untouchable. That the gap was the competitive advantage. OpenClaw cracked that. Not by having a better model. By proving that for most real-world tasks, cheaper models running locally on a Mac Mini are good enough. The cloud becomes optional. The premium becomes hard to justify. The competition has shifted. It's not about who has the best model anymore. It's about who builds the best layer on top of it. Agents, workflows, things that actually do work instead of just answering questions. The value is shifting away from the model and toward the layer you build on top of it. The chat interface was just the lobby. We're in the building now.`
  },
  {
    id: "06",
    published: true,
    date: "Mar 2026",
    tag: "AI",
    title: "Most Enterprise AI Projects Don't Fail Because the Tech Is Bad",
    excerpt: "Mistral's Forge bets on a simple, uncomfortable idea: enterprise AI fails not because the model is weak, but because it was trained on the internet and not on your company.",
    file: "bit-06.html",
    readTime: "4 min",
    author: "Matteo Favilli",
    linkedin: "https://www.linkedin.com/posts/matteo-favilli_ai-proprietaryai-aistrategy-share-7440050534117449728-cxGL",
    text: `Mistral AI just bet that owning AI beats renting it. The idea behind Forge is simple and a bit uncomfortable for the industry: most enterprise AI projects don't fail because the technology isn't there. They fail because the model has no idea how the company actually works. Trained on the internet. Not on your contracts, your processes, the ten years of institutional knowledge buried in documents nobody outside your walls has ever read. I keep having the same conversation with clients in pharma and life sciences. It's never 'should we use AI'. It's always 'we tried, but the model didn't understand our context, gave answers that made sense in general but were wrong for us specifically'. That's not a technology gap. That's a training data problem. Fine-tuning and RAG don't really fix it completely. They make it less visible. The model is still fundamentally someone else's model, shaped by someone else's assumptions. Owning the model changes the equation. Trained on your knowledge, governed by your policies, inside your infrastructure. In regulated industries, where you can't afford to not understand why the model said what it said, the direction makes sense. Whether most organizations are actually ready to get there is a different story.`
  },
  {
    id: "07",
    published: false,
    date: "Apr 2026",
    tag: "Innovation",
    title: "Dario Amodei Moves to Italy",
    excerpt: "The Anthropic CEO announced he is moving to Massa Marittima, Tuscany. A short thought on what this signals.",
    file: "",
    readTime: "2 min",
    author: "Matteo Favilli",
    text: `Ci vediamo in Piazza Dario. Anthropic CEO Dario Amodei announced he is moving to Massa Marittima, a small town in Tuscany, his father's hometown. He will lead Anthropic in full remote for 6 months a year from the Maremma.`
  }
];
